import = [
"~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

#[shell]
#program="/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
#padding.x = 10
#padding.y = 10

#decorations = "Transparent"

opacity = 1.0
#blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

size = 13
